# Generated by Django 5.0.2 on 2024-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.TextField(max_length=20)),
                ('child_age', models.CharField(default='', max_length=2)),
                ('image1', models.ImageField(default=None, upload_to='media_storage/main_page_images')),
                ('image2', models.ImageField(default=None, upload_to='media_storage/main_page_images')),
                ('image3', models.ImageField(default=None, upload_to='media_storage/main_page_images')),
                ('image4', models.ImageField(default=None, upload_to='media_storage/main_page_images')),
                ('image5', models.ImageField(default=None, upload_to='media_storage/main_page_images')),
                ('image6', models.ImageField(default=None, upload_to='media_storage/main_page_images')),
                ('image1_url_new', models.URLField()),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('it', 'Italiano'), ('ru', 'Русский')], default='uk', max_length=30)),
            ],
        ),
    ]
