# Generated by Django 5.0.2 on 2024-04-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPageSettings',
            new_name='MainPageSetting',
        ),
    ]
