# Generated by Django 5.0.3 on 2024-06-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_mainpagesetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagesetting',
            name='child_age',
            field=models.CharField(default='2 роки', max_length=15, verbose_name='Вік дитини'),
        ),
    ]
