# Generated by Django 5.0.2 on 2024-05-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default=' ', max_length=150, verbose_name="Ім'я"),
        ),
    ]
