# Generated by Django 5.0.2 on 2024-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media_storage/reviews_images', verbose_name="Фото(не обов'язково)"),
        ),
        migrations.AlterField(
            model_name='review',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('it', 'Italiano'), ('ru', 'Русский')], default='uk', max_length=30, verbose_name='Мова сайту'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(max_length=100, verbose_name='Відгук'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name="Ім'я"),
        ),
    ]
