# Generated by Django 5.0.2 on 2024-05-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_image_alter_review_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
    ]
