# Generated by Django 5.0.2 on 2024-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_review_created_at_alter_review_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(max_length=200, verbose_name='Відгук'),
        ),
    ]
