# Generated by Django 5.0.2 on 2024-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_with_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(editable=False, max_length=255)),
                ('phone', models.CharField(editable=False, max_length=12)),
                ('message', models.TextField(editable=False)),
                ('selected_button', models.TextField(default=' ', editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
