# Generated by Django 5.0.2 on 2024-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_with_us', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrequest',
            name='phone',
            field=models.CharField(editable=False, max_length=13),
        ),
    ]
