# Generated by Django 5.0.2 on 2024-05-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_with_us', '0004_alter_usersrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersrequest',
            options={'verbose_name': 'Повідомлення користувача', 'verbose_name_plural': 'Повідомлення користувачів'},
        ),
    ]
