# Generated by Django 5.0.2 on 2024-04-04 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('short_description', models.TextField(max_length=200)),
                ('content', models.TextField()),
                ('time_to_read', models.CharField(default='10', max_length=5)),
                ('main_image', models.ImageField(upload_to='media_storage/news_images')),
                ('optional_image_1', models.ImageField(blank=True, upload_to='media_storage/news_images')),
                ('optional_image_2', models.ImageField(blank=True, upload_to='media_storage/news_images')),
                ('optional_image_3', models.ImageField(blank=True, upload_to='media_storage/news_images')),
                ('category', models.CharField(choices=[('childs_history', 'Історії діток'), ('fond_achievments', 'Досягнення фонду'), ('important', 'Важливе'), ('your_help', 'Ваша допомога'), ('life_of_fond', 'Життя фонду'), ('interview', 'Інтерв’ю')], default='important', max_length=25)),
                ('slug', models.SlugField(default='', unique=True)),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('it', 'Italiano'), ('ru', 'Русский')], default='uk', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
