# Generated by Django 5.0.2 on 2024-05-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('childs_history', 'Історії діток'), ('fond_achievments', 'Досягнення фонду'), ('important', 'Важливе'), ('your_help', 'Ваша допомога'), ('life_of_fond', 'Життя фонду'), ('interview', 'Інтерв’ю')], default='important', max_length=25, verbose_name='Категорія новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Текст новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(upload_to='media_storage/news_images', verbose_name="Фото 1 (обов'язково)"),
        ),
        migrations.AlterField(
            model_name='news',
            name='optional_image_1',
            field=models.ImageField(blank=True, upload_to='media_storage/news_images', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='news',
            name='optional_image_2',
            field=models.ImageField(blank=True, upload_to='media_storage/news_images', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='news',
            name='optional_image_3',
            field=models.ImageField(blank=True, upload_to='media_storage/news_images', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=200, verbose_name='Скорочений текст '),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Slug сторінки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_to_read',
            field=models.CharField(default='10', max_length=5, verbose_name='Час прочитання'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
