# Generated by Django 5.0.2 on 2024-09-04 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options_alter_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.URLField(blank=True, default=' ', null=True, verbose_name='Посилання на YouTube:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('evacuation', 'Евакуація'), ('fond_achievments', 'Досягнення фонду'), ('clinic', 'Клініка'), ('your_help', 'Ваша допомога'), ('life_of_fond', 'Життя фонду'), ('interview', 'Інтерв’ю'), ('important', 'Важливе')], default='', max_length=25, verbose_name='Категорія новини'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення:'),
        ),
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('it', 'Italiano'), ('ru', 'Русский')], default='uk', max_length=30, verbose_name='Мова сайту'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=200, verbose_name='Скорочений текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True, verbose_name='Slug сторінки'),
        ),
    ]
