# Generated by Django 5.0.2 on 2024-04-04 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email_data', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LiqpayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(editable=False, null=True)),
                ('currency', models.CharField(default='UAH', editable=False, max_length=4)),
                ('email_data', models.EmailField(editable=False, max_length=254)),
                ('phone', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(editable=False, max_length=15)),
                ('last_name', models.CharField(editable=False, max_length=20)),
                ('description', models.TextField(editable=False)),
                ('status', models.CharField(editable=False, max_length=255)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hashed_order_id', models.CharField(default=' ', editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Liqpay Payments',
            },
        ),
    ]
