# Generated by Django 5.0.2 on 2024-04-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_services', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalpayment',
            old_name='email_data',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='liqpaypayment',
            old_name='email_data',
            new_name='email',
        ),
    ]
