# Generated by Django 5.0.2 on 2024-05-10 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_services', '0003_rename_email_data_internationalpayment_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationalpayment',
            options={'verbose_name': 'Міжнародний переказ', 'verbose_name_plural': 'Міжнародні перекази'},
        ),
        migrations.AlterModelOptions(
            name='liqpaypayment',
            options={'verbose_name': 'Платіж Liqpay', 'verbose_name_plural': 'Платежі Liqpay'},
        ),
        migrations.AlterField(
            model_name='internationalpayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='internationalpayment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='internationalpayment',
            name='name',
            field=models.CharField(max_length=30, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='internationalpayment',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='internationalpayment',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамілія'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='amount',
            field=models.IntegerField(editable=False, null=True, verbose_name='Сума'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='currency',
            field=models.CharField(default='UAH', editable=False, max_length=4, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='description',
            field=models.TextField(editable=False, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='email',
            field=models.EmailField(editable=False, max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='hashed_order_id',
            field=models.CharField(default=' ', editable=False, max_length=255, unique=True, verbose_name='Закодований ID платежу'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='last_name',
            field=models.CharField(editable=False, max_length=20, verbose_name='Фамілія'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='name',
            field=models.CharField(editable=False, max_length=15, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежу'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='phone',
            field=models.CharField(editable=False, max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='liqpaypayment',
            name='status',
            field=models.CharField(editable=False, max_length=255, verbose_name='Статус'),
        ),
    ]
