# Generated by Django 5.0.2 on 2024-05-02 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='name',
            new_name='partner_name',
        ),
    ]
