# Generated by Django 5.0.2 on 2024-04-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendEmailToAllSubscribedUsers',
            new_name='SendEmailToAllSubscribedUser',
        ),
        migrations.RenameModel(
            old_name='SubscribedUsersEmails',
            new_name='SubscribedUsersEmail',
        ),
        migrations.RenameField(
            model_name='subscribedusersemail',
            old_name='email_data',
            new_name='email',
        ),
    ]
