# Generated by Django 5.0.2 on 2024-05-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0004_alter_sendemailtoallsubscribeduser_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemailtoallsubscribeduser',
            options={'verbose_name': 'Розсилка', 'verbose_name_plural': 'Відправити розсилку для всіх користувачів'},
        ),
        migrations.AlterModelOptions(
            name='subscribedusersemail',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'База підписаних користувачів на Email-розсилку'},
        ),
    ]
