# Generated by Django 5.0.3 on 2024-06-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0005_alter_sendemailtoallsubscribeduser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendemailtoallsubscribeduser',
            options={'verbose_name': 'Розсилка', 'verbose_name_plural': 'Розсилки'},
        ),
    ]
