# Generated by Django 5.0.2 on 2024-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports_and_Our_Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default=2024, max_length=4)),
                ('first_description', models.TextField(default='', max_length=255)),
                ('second_description', models.TextField(default='', max_length=255)),
                ('third_description', models.TextField(default='', max_length=255)),
                ('first_diagram_percent', models.PositiveSmallIntegerField(default=0)),
                ('second_diagram_percent', models.PositiveSmallIntegerField(default=0)),
                ('third_diagram_percent', models.PositiveSmallIntegerField(default=0)),
                ('statement_file', models.FileField(default='', upload_to='media_storage/financial_files')),
                ('statement_file_name', models.TextField(default=' ', max_length=30)),
                ('article_title', models.CharField(max_length=50)),
                ('article_title_link', models.URLField(default='')),
                ('article_content', models.TextField()),
                ('article_image', models.ImageField(upload_to='media_storage/financial_files')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('it', 'Italiano'), ('ru', 'Русский')], default='uk', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleOnSite',
        ),
        migrations.DeleteModel(
            name='FinancialStatement',
        ),
    ]
