# Generated by Django 5.0.2 on 2024-04-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reports_and_our_articles_delete_articleonsite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports_and_Our_Articles',
            new_name='ReportsAndOurArticle',
        ),
    ]
