# Generated by Django 5.0.2 on 2024-04-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_rename_reports_and_our_articles_reportsandourarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsandourarticle',
            name='statement_file',
            field=models.FileField(default='', max_length=25, upload_to='media_storage/financial_files'),
        ),
    ]
