# Generated by Django 5.0.2 on 2024-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_reportsandourarticle_statement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsandourarticle',
            name='statement_file',
            field=models.FileField(default='', upload_to='media_storage/financial_files'),
        ),
        migrations.AlterField(
            model_name='reportsandourarticle',
            name='statement_file_name',
            field=models.TextField(default=' ', max_length=50),
        ),
    ]
