# Generated by Django 5.0.2 on 2024-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_reportsandourarticle_statement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsandourarticle',
            name='statement_file_name',
            field=models.TextField(default=' ', max_length=70),
        ),
    ]
