# Generated by Django 5.0.2 on 2024-04-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_reportsandourarticle_statement_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50)),
                ('article_title_link', models.URLField(default='')),
                ('article_content', models.TextField()),
                ('article_image', models.ImageField(upload_to='media_storage/financial_files')),
                ('language', models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('it', 'Italiano'), ('ru', 'Русский')], default='uk', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportsandourarticle',
            name='article_content',
        ),
        migrations.RemoveField(
            model_name='reportsandourarticle',
            name='article_image',
        ),
        migrations.RemoveField(
            model_name='reportsandourarticle',
            name='article_title',
        ),
        migrations.RemoveField(
            model_name='reportsandourarticle',
            name='article_title_link',
        ),
    ]
