# Generated by Django 5.0.2 on 2024-04-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_ourarticle_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportsAndOurArticle',
            new_name='Reports',
        ),
    ]
