# Generated by Django 5.0.2 on 2024-04-05 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rename_reportsandourarticle_reports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
