# Generated by Django 5.0.2 on 2024-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_rename_reports_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fourth_diagram_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='second_diagram_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='third_diagram_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
