# Generated by Django 5.0.2 on 2024-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_report_fourth_diagram_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fourth_description',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='second_description',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='third_description',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
