# Generated by Django 5.0.2 on 2024-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_report_fourth_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='first_diagram_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='fourth_diagram_percent',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='second_diagram_percent',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='third_diagram_percent',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
    ]
