# Generated by Django 5.0.2 on 2024-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_report_first_diagram_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='statement_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media_storage/financial_files'),
        ),
    ]
