# Generated by Django 5.0.2 on 2024-05-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_report_statement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='statement_file_name',
            field=models.TextField(blank=True, default=None, max_length=70, null=True),
        ),
    ]
