# Generated by Django 5.0.2 on 2024-05-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_report_statement_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourarticle',
            options={'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Звіт', 'verbose_name_plural': 'Звіти'},
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='article_content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='article_image',
            field=models.ImageField(upload_to='media_storage/financial_files', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='article_title',
            field=models.CharField(max_length=50, verbose_name='Заголовок статті'),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='article_title_link',
            field=models.URLField(default='', verbose_name='Посилання на статтю'),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('it', 'Italiano'), ('ru', 'Русский')], default='uk', max_length=30, verbose_name='Мова сайту'),
        ),
        migrations.AlterField(
            model_name='report',
            name='first_description',
            field=models.TextField(default='', max_length=255, verbose_name="Пункт 1 (обов'язковий)"),
        ),
        migrations.AlterField(
            model_name='report',
            name='first_diagram_percent',
            field=models.FloatField(default=0, verbose_name='Відсоток пункту 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fourth_description',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Пункт 4'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fourth_diagram_percent',
            field=models.FloatField(blank=True, default=0, verbose_name='Відсоток пункту 4'),
        ),
        migrations.AlterField(
            model_name='report',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('en', 'English'), ('it', 'Italiano'), ('ru', 'Русский')], default='uk', max_length=30, verbose_name='Мова сайту'),
        ),
        migrations.AlterField(
            model_name='report',
            name='second_description',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Пункт 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='second_diagram_percent',
            field=models.FloatField(blank=True, default=0, verbose_name='Відсоток пункту 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='statement_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media_storage/financial_files', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='report',
            name='statement_file_name',
            field=models.TextField(blank=True, default=None, max_length=70, null=True, verbose_name='Назва для файлу для звіту'),
        ),
        migrations.AlterField(
            model_name='report',
            name='third_description',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Пункт 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='third_diagram_percent',
            field=models.FloatField(blank=True, default=0, verbose_name='Відсоток пункту 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.CharField(default='2024', max_length=4, verbose_name='Рік'),
        ),
    ]
